### ISSUE TITLE
No rake error with Heroku build

### ISSUE THREAD

**Issue by beschne** [beschne/witzmaschine#33]
```
-----> Detecting rake tasks
       Could not detect rake tasks
       ensure you can run `$ bundle exec rake -P` against your app
       and using the production group of your Gemfile.
       rake aborted!
       LoadError: cannot load such file -- rspec/core/rake_task
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/Rakefile:3:in `<top (required)>'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
       /tmp/build_9d614fcac82e9db8254a0b39e3b48744/beschne-witzmaschine-4d6964e/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
       vendor/ruby-2.2.0/bin/rake:37:in `<main>'
```

**Comment by beschne** [comment]
This error occurs because rspec is not in my Gemfile production group.
http://stackoverflow.com/questions/29732542/heroku-could-not-detect-rake-tasks-loaderror-cannot-load-such-file-rspec-co
